config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chats#index'

  resources :chats
  resources :messages

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: :User, foreign_key: :sender_id
  belongs_to :receiver, class_name: :User, foreign_key: :receiver_id
  validates :body, presence: true

  #after_create_commit :broadcast_message

  private

  def broadcast_message
    MessageBroadcastJob.perform_later(self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  has_many :send_messages, class_name: :Message, foreign_key: :sender_id
  has_many :received_messages, class_name: :Message, foreign_key: :receiver_id
  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
    @messages = Message.order(created_at: :asc)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @receiver_id = params[:receiver_id]
    send_messages =  Message.where("sender_id = ? and receiver_id = ?",
                                   current_user.id, params[:receiver_id])
    receiver_message = Message.where("sender_id = ? and receiver_id = ?",
                                     params[:receiver_id], current_user.id)
    @messages = (send_messages + receiver_message).sort
  end

  def create
    @message = current_user.send_messages.create(body: params[:body], receiver_id: params['receiver_id'].to_i)
    ActionCable.server.broadcast 'chat_channel', message: render_message(@message)
  end

  private

  def render_message(message)
    render partial: 'messages/message', locals: {message: message}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/index.html.erb
<h1> Inbox </h1>
<% User.all.each do |user|%>
  <% if user.id != current_user.id %>
    <strong><%= user&.username%>: <%= link_to "Let's chat", messages_path(receiver_id: user.id)%> </strong></br></br>  
  <% end %>
    <%#= hidden_field_tag 'receiver_id',  %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableUploader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to "Sign out", destroy_user_session_path, method: 'delete' %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <%= tag.div value, class: "flash #{key}" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="messageids" data-sender-id="<%= message.sender.id%>"></div>
  <% if message.sender.email == current_user.email %>
    <div class="messsage-content" style= "text-align: right">
      <strong><%= message.sender.email %></strong> says:
      <%= message.body %>
      <br>
      <small>at <%= l message.created_at, format: :short %></small>
    </div> 
  <% else %>
    <div class="messsage-content" style= "text-align: left">
      <strong><%= message.sender.email %></strong> says:
      <%= message.body %>
      <br>
      <small>at <%= l message.created_at, format: :short %></small>
    </div>  
  <% end %> 
  <hr>
</div>

app/views/messages/create.js.erb
$("#messages").append("<%= j(render 'messages/message') %>");

app/views/messages/index.html.erb
<div id="messages">
  <%= render @messages %>
  <div class="logged-user" data-logged-user="<%= current_user.id%>"></div>
</div>
<%= form_with url: '/messages', method: :post, remote: true, html: {id: 'new-message'} do |f| %>
  <h2>New Message</h2>
  <%= f.label :body %>
  <%= f.text_area :body, id: 'message-body' %>
  <%= f.hidden_field :receiver_id, value: params[:receiver_id] %>
  <%= f.hidden_field :sender_id, value: current_user.id %>
  <br>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>